import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const dictionary = {
    en: {
        // Navbar
        home: 'Home',
        aboutUs: 'About Us',
        signedInAs: 'Signed in as',
        changeName: 'Change Name',
        changePassword: 'Change Password',
        deleteAccount: 'Delete Account',
        about: 'About Us',
        ourSolutions: 'Our Solutions',
        contact: 'Contact',
        careers: 'Careers',

        // Home
        welcome_title: 'Welcome to GreenTrack',
        welcome_subtitle: 'Track your carbon footprint, manage your plant collection, and contribute to a greener planet. Join our community today.',
        login_btn: 'Login',
        learn_more_btn: 'Learn More',
        topSaversTitle: 'Top Carbon Savers',
        topSaversSubtitle: 'Meet the heroes leading the fight against climate change with the most carbon saved.',
        kgCO2Saved: 'kg CO₂ saved',
        plant_tracking_title: 'Plant Tracking',
        plant_tracking_desc: 'Monitor the health and growth of your personal plant collection with ease.',
        carbon_impact_title: 'Carbon Impact',
        carbon_impact_desc: 'Visualize how your green collection contributes to reducing CO2 levels.',
        global_ranking_title: 'Global Ranking',
        global_ranking_desc: 'See where you stand among other eco-conscious members worldwide.',

        // About
        about_title: 'About GreenTrack',
        about_mission: 'GreenTrack was founded with a simple yet powerful mission: to empower individuals to make a tangible difference in the fight against climate change through the simple act of planting and caring for trees and plants.',
        about_vision_desc: 'We believe that technology can bridge the gap between individual action and global impact. By tracking your plant collection, calculating carbon offsets, and connecting with a community of like-minded individuals, GreenTrack turns gardening into a global movement.',
        our_vision_title: 'Our Vision',
        our_vision_statement: 'A world where every individual is a steward of the environment, and where our collective green efforts actively restore the balance of our planet\'s ecosystem.',
        sustainability_first: 'Sustainability First',
        sustainability_desc: 'Every feature we build is designed to promote long-term ecological health.',
        community_driven: 'Community Driven',
        community_desc: 'We grow stronger together, sharing knowledge and celebrating milestones.',
        meet_designers: 'Meet Our Designers',
        lead_designer: 'Full Stack Developer',
        creative_director: 'Software Engineer',
        advisor: 'Advisor',

        full_stack_dev: 'Full Stack Developer',

        // Contact
        contact_title: 'Contact Us',
        contact_subtitle: 'We\'d love to hear from you. Send us a message below.',
        name_label: 'Name',
        name_placeholder: 'Your Name',
        email_label: 'Email',
        email_placeholder: 'your@email.com',
        subject_label: 'Subject',
        subject_placeholder: 'What is this regarding?',
        message_label: 'Message',
        message_placeholder: 'Your message here...',
        send_message_btn: 'Send Message',
        message_sent_title: 'Message Sent!',
        message_sent_desc: 'Thank you for reaching out. We\'ll get back to you shortly.',
        send_another_btn: 'Send another message',

        // Dashboard
        myPlants: 'My Plants',
        managePlants: 'Manage and track your plant collection.',
        addPlant: 'Add Plant',
        carbonReduction: 'Carbon Reduction',
        homeAtmosphere: "Home's Atmosphere",
        atmosphereGood: 'Good',
        atmosphereModerate: 'Moderate',
        atmospherePoor: 'Poor',
        emptyStateTitle: "You haven't added any plants yet.",
        emptyStateSubtitle: "Click the 'Add Plant' button to get started!",
        viewDetails: 'View Details',
        healthy: 'Healthy',
        needsWater: 'Needs Water',
        addPlantTitle: 'Add a New Plant',
        plantName: 'Plant Name',
        plantNamePlaceholder: 'e.g. My Rose',
        plantType: 'Plant Type',
        selectPlantType: 'Select a type…',
        typeOrSelectPlantType: 'Type or select a plant type…',
        addCustomType: 'Add new type:',
        noTypesFound: 'No types found',
        cancel: 'Cancel',
        saving: 'Saving…',
        save: 'Save',
        species: 'Species (Optional)',
        wateringFrequency: 'Watering Frequency (in days)',

        // Plant type name translations
        plantTypeNames: {
            'Monstera': 'Monstera',
            'Pothos': 'Pothos',
            'Snake Plant': 'Snake Plant',
            'Spider Plant': 'Spider Plant',
            'Peace Lily': 'Peace Lily',
            'Ficus': 'Ficus',
            'Orchid': 'Orchid',
            'Bonsai': 'Bonsai',
            'Aloe Vera': 'Aloe Vera',
            'Philodendron': 'Philodendron',
            'Calathea': 'Calathea',
            'Ivy': 'Ivy',
            'Jade Plant': 'Jade Plant',
            'ZZ Plant': 'ZZ Plant',
            'Begonia': 'Begonia',
            'Dracaena': 'Dracaena',
            'Tulip': 'Tulip',
            'Air Plant': 'Air Plant',
            'Bamboo': 'Bamboo',
            'Citrus Tree': 'Citrus Tree',
            'Cactus': 'Cactus',
            'Anthurium': 'Anthurium',
            'Dieffenbachia': 'Dieffenbachia',
            'Peperomia': 'Peperomia',
            'Croton': 'Croton',
            'Aglaonema': 'Aglaonema',
            'Chinese Money Plant': 'Chinese Money Plant',
            'Fittonia': 'Fittonia',
            'Syngonium': 'Syngonium',
            'Wax Plant': 'Wax Plant',
            'Tradescantia': 'Tradescantia',
            'Asparagus Fern': 'Asparagus Fern',
            'Bromeliad': 'Bromeliad',
            'Cast Iron Plant': 'Cast Iron Plant',
            'Parlor Palm': 'Parlor Palm',
            'Areca Palm': 'Areca Palm',
            'Ponytail Palm': 'Ponytail Palm',
            'Yucca': 'Yucca',
            'African Violet': 'African Violet',
            'Cyclamen': 'Cyclamen',
            'Kalanchoe': 'Kalanchoe',
            'Mint': 'Mint',
            'Basil': 'Basil',
            'Rosemary': 'Rosemary',
            'Lavender': 'Lavender',
            'Geranium': 'Geranium',
            'Hibiscus': 'Hibiscus',
            'Bougainvillea': 'Bougainvillea',
            'Chrysanthemum': 'Chrysanthemum',
            'Poinsettia': 'Poinsettia',
            'Fern': 'Fern',
            'Bird of Paradise': 'Bird of Paradise',
            'String of Pearls': 'String of Pearls',
            'String of Hearts': 'String of Hearts',
            'Money Tree': 'Money Tree',
            'Rubber Plant': 'Rubber Plant',
            'Lithops': 'Lithops',
            'Echeveria': 'Echeveria',
            'Haworthia': 'Haworthia',
            'Sedum': 'Sedum',
            'Pilea': 'Pilea',
            'Zamioculcas': 'Zamioculcas',
            'Maranta': 'Maranta',
            'Stromanthe': 'Stromanthe',
            'Alocasia': 'Alocasia',
            'Colocasia': 'Colocasia',
            'Caladium': 'Caladium',
            'Polyscias': 'Polyscias',
            'Schefflera': 'Schefflera',
            'Nephrolepis': 'Nephrolepis',
            'Asplenium': 'Asplenium',
            'Platycerium': 'Platycerium',
            'Adiantum': 'Adiantum',
            'Pteris': 'Pteris',
            'Blechnum': 'Blechnum',
            'Cycas': 'Cycas',
            'Rhapis': 'Rhapis',
            'Howea': 'Howea',
            'Phoenix': 'Phoenix',
            'Washingtonia': 'Washingtonia',
            'Caryota': 'Caryota',
            'Musa': 'Musa',
            'Strelitzia': 'Strelitzia',
            'Heliconia': 'Heliconia',
            'Canna': 'Canna',
            'Zingiber': 'Zingiber',
            'Curcuma': 'Curcuma',
            'Alpinia': 'Alpinia',
            'Costus': 'Costus',
            'Calathea Makoyana': 'Calathea Makoyana',
            'Ctenanthe': 'Ctenanthe',
            'Oxalis': 'Oxalis',
            'Senecio': 'Senecio',
            'Ceropegia': 'Ceropegia',
            'Dischidia': 'Dischidia',
            'Aeschynanthus': 'Aeschynanthus',
            'Columnea': 'Columnea',
            'Episcia': 'Episcia',
            'Streptocarpus': 'Streptocarpus',
            'Sinningia': 'Sinningia',
            'Primula': 'Primula',
            'Viola': 'Viola',
            'Petunia': 'Petunia',
            'Pelargonium': 'Pelargonium',
            'Fuchsia': 'Fuchsia',
            'Impatiens': 'Impatiens',
            'Begonia Maculata': 'Begonia Maculata',
            'Pachypodium': 'Pachypodium',
            'Adenium': 'Adenium',
            'Hoya': 'Hoya',
            'Araucaria': 'Araucaria',
            'Pachira': 'Pachira',
            'Rhoeo': 'Rhoeo',
            'Coleus': 'Coleus',
            'Iresine': 'Iresine',
            'Gynura': 'Gynura',
            'Hemigraphis': 'Hemigraphis',
        },

        // Footer
        mission: 'We work with the power of technology and community for a sustainable future.',
        copyright: '© 2026 GreenTrack - All rights reserved.',
        platform: 'PLATFORM',
        corporate: 'CORPORATE',

        // Auth (Login/Signup/Forgot Password)
        welcome_back: 'Welcome Back',
        sign_in_subtitle: 'Sign in to your account',
        email_address_label: 'Email Address',
        password_label: 'Password',
        confirm_password_label: 'Confirm Password',
        remember_me: 'Remember me',
        forgot_password: 'Forgot password?',
        sign_in_btn: 'Login',
        no_account: "Don't have an account?",
        sign_up: 'Sign Up',
        create_account_title: 'Create Account',
        join_today: 'Join GreenTrack today',
        full_name_placeholder: 'Full Name',
        password_placeholder: 'Password',
        confirm_password_placeholder: 'Confirm Password',
        uploadPhoto: 'Upload Photo',
        photoTooLarge: 'Photo must be under 2 MB',
        create_account_btn: 'Create Account',
        already_have_account: 'Already have an account?',
        sign_in_link: 'Sign In',
        reset_password_title: 'Reset Password',
        reset_password_subtitle: 'Enter your email to receive a reset link',
        send_reset_link_btn: 'Send Reset Link',
        check_email_title: 'Check your email',
        check_email_desc: 'If an account exists for that email, we have sent password reset instructions.',
        back_to_login: 'Back to Login',
        logout: 'Logout',
        logoutConfirmTitle: 'Log Out?',
        logoutConfirmMessage: 'Are you sure you want to log out?',
        verify_code_title: 'Verify Code',
        verify_code_subtitle: 'Enter the 6-digit code sent to your email',
        verify_btn: 'Verify',
        new_password_title: 'Set New Password',
        new_password_subtitle: 'Enter your new password below',
        new_password_placeholder: 'New Password',
        reset_password_btn: 'Reset Password',
        password_reset_success: 'Password Reset Successful!',
        redirecting_to_login: 'Redirecting to login…',

        // Signup error/success messages
        error_email_registered: 'This email is already registered!',
        error_passwords_not_match: 'Passwords do not match!',
        error_server_connection: 'Could not connect to the server. Is Spring Boot running?',
        registration_success_title: 'Registration Successful!',
        redirecting_to_dashboard: 'Redirecting to your dashboard...',
    },
    tr: {
        // Navbar
        home: 'Ana Sayfa',
        aboutUs: 'Hakkımızda',
        signedInAs: 'Oturum açan:',
        changeName: 'İsim Değiştir',
        changePassword: 'Şifre Değiştir',
        deleteAccount: 'Hesabı Sil',
        about: 'Hakkımızda',
        ourSolutions: 'Çözümlerimiz',
        contact: 'İletişim',
        careers: 'Kariyer',

        // Home
        welcome_title: 'GreenTrack\'e Hoş Geldiniz',
        welcome_subtitle: 'Karbon ayak izinizi takip edin, bitki koleksiyonunuzu yönetin ve daha yeşil bir gezegene katkıda bulunun. Topluluğumuza bugün katılın.',
        login_btn: 'Giriş Yap',
        learn_more_btn: 'Daha Fazla',
        topSaversTitle: 'En Çok Karbon Tasarrufu Yapanlar',
        topSaversSubtitle: 'İklim değişikliğine karşı mücadelede en çok karbonu tasarruf eden kahramanlarla tanışın.',
        kgCO2Saved: 'kg CO₂ tasarruf edildi',
        plant_tracking_title: 'Bitki Takibi',
        plant_tracking_desc: 'Kişisel bitki koleksiyonunuzun sağlığını ve büyümesini kolayca izleyin.',
        carbon_impact_title: 'Karbon Etkisi',
        carbon_impact_desc: 'Yeşil koleksiyonunuzun CO2 seviyelerini düşürmeye nasıl katkıda bulunduğunu görselleştirin.',
        global_ranking_title: 'Küresel Sıralama',
        global_ranking_desc: 'Dünya çapındaki diğer çevre bilincine sahip üyeler arasında nerede olduğunuzu görün.',

        // About
        about_title: 'GreenTrack Hakkında',
        about_mission: 'GreenTrack, basit ama güçlü bir misyonla kuruldu: bireyleri ağaç ve bitki dikip bakımını yaparak iklim değişikliğine karşı mücadelede somut bir fark yaratmaları için güçlendirmek.',
        about_vision_desc: 'Teknolojinin bireysel eylem ile küresel etki arasındaki boşluğu doldurabileceğine inanıyoruz. Bitki koleksiyonunuzu takip ederek, karbon denkleştirmelerini hesaplayarak ve benzer düşünen bireylerden oluşan bir toplulukla bağlantı kurarak GreenTrack, bahçeciliği küresel bir harekete dönüştürüyor.',
        our_vision_title: 'Vizyonumuz',
        our_vision_statement: 'Her bireyin çevrenin bir koruyucusu olduğu ve kolektif yeşil çabalarımızın gezegenimizin ekosisteminin dengesini aktif olarak onardığı bir dünya.',
        sustainability_first: 'Önce Sürdürülebilirlik',
        sustainability_desc: 'Oluşturduğumuz her özellik, uzun vadeli ekolojik sağlığı teşvik etmek için tasarlanmıştır.',
        community_driven: 'Topluluk Odaklı',
        community_desc: 'Birlikte güçleniyor, bilgiyi paylaşıyor ve dönüm noktalarını kutluyoruz.',
        meet_designers: 'Tasarımcılarımızla Tanışın',
        lead_designer: 'Full Stack Developer',
        creative_director: 'Software Engineer',
        advisor: 'Danışman',

        // Contact
        contact_title: 'Bize Ulaşın',
        contact_subtitle: 'Sizden haber almayı çok isteriz. Aşağıdan bize bir mesaj gönderin.',
        name_label: 'İsim',
        name_placeholder: 'İsminiz',
        email_label: 'E-posta',
        email_placeholder: 'senin@epostan.com',
        subject_label: 'Konu',
        subject_placeholder: 'Bu ne hakkında?',
        message_label: 'Mesaj',
        message_placeholder: 'Mesajınız...',
        send_message_btn: 'Mesaj Gönder',
        message_sent_title: 'Mesaj Gönderildi!',
        message_sent_desc: 'Bize ulaştığınız için teşekkürler. Kısa süre içinde size geri döneceğiz.',
        send_another_btn: 'Başka bir mesaj gönder',

        // Dashboard
        myPlants: 'Bitkilerim',
        managePlants: 'Bitki koleksiyonunuzu yönetin ve takip edin.',
        addPlant: 'Bitki Ekle',
        carbonReduction: 'Karbon Azaltımı',
        homeAtmosphere: 'Evin Hafası',
        atmosphereGood: 'İyi',
        atmosphereModerate: 'Orta',
        atmospherePoor: 'Kötü',
        emptyStateTitle: "Henüz hiç bitki eklemediniz.",
        emptyStateSubtitle: "Başlamak için 'Bitki Ekle' butonuna tıklayın!",
        viewDetails: 'Detayları Gör',
        healthy: 'Sağlıklı',
        needsWater: 'Su İhtiyacı Var',
        addPlantTitle: 'Yeni Bitki Ekle',
        plantName: 'Bitki Adı',
        plantNamePlaceholder: 'örn. Gülüm',
        plantType: 'Bitki Türü',
        selectPlantType: 'Bir tür seçin…',
        typeOrSelectPlantType: 'Bitki türü yazın veya seçin…',
        addCustomType: 'Yeni tür ekle:',
        noTypesFound: 'Tür bulunamadı',
        cancel: 'İptal',
        saving: 'Kaydediliyor…',
        save: 'Kaydet',
        species: 'Tür (İsteğe Bağlı)',
        wateringFrequency: 'Sulama Sıklığı (Gün Olarak)',

        // Plant type name translations
        plantTypeNames: {
            'Monstera': 'Deve Tabanı',
            'Pothos': 'Potos',
            'Snake Plant': 'Yılan Bitkisi',
            'Spider Plant': 'Örümcek Bitkisi',
            'Peace Lily': 'Barış Zambağı',
            'Ficus': 'Kauçuk Ağacı',
            'Orchid': 'Orkide',
            'Bonsai': 'Bonsai',
            'Aloe Vera': 'Aloe Vera',
            'Philodendron': 'Filodendron',
            'Calathea': 'Kalatea',
            'Ivy': 'Sarmaşık',
            'Jade Plant': 'Para Çiçeği',
            'ZZ Plant': 'ZZ Bitkisi',
            'Begonia': 'Begonya',
            'Dracaena': 'Drasena',
            'Tulip': 'Lale',
            'Air Plant': 'Hava Bitkisi',
            'Bamboo': 'Bambu',
            'Citrus Tree': 'Narenciye Ağacı',
            'Cactus': 'Kaktüs',
            'Anthurium': 'Flamingo Çiçeği',
            'Dieffenbachia': 'Difenbahya',
            'Peperomia': 'Zümrüt Dalı',
            'Croton': 'Kroton',
            'Aglaonema': 'Çin Herdemyeşili',
            'Chinese Money Plant': 'Çin Para Çiçeği',
            'Fittonia': 'Mozaik Çiçeği',
            'Syngonium': 'Melek Kanadı',
            'Wax Plant': 'Mum Çiçeği',
            'Tradescantia': 'Telgraf Çiçeği',
            'Asparagus Fern': 'Kuşkonmaz Eğreltisi',
            'Bromeliad': 'Bromelya',
            'Cast Iron Plant': 'Salon Yaprağı',
            'Parlor Palm': 'Dağ Palmiyesi',
            'Areca Palm': 'Areka Palmiyesi',
            'Ponytail Palm': 'Fil Ayağı',
            'Yucca': 'Yuka',
            'African Violet': 'Afrika Menekşesi',
            'Cyclamen': 'Sıklamen',
            'Kalanchoe': 'Kalanşo',
            'Mint': 'Nane',
            'Basil': 'Fesleğen',
            'Rosemary': 'Biberiye',
            'Lavender': 'Lavanta',
            'Geranium': 'Sardunya',
            'Hibiscus': 'Japon Gülü',
            'Bougainvillea': 'Begonvil',
            'Chrysanthemum': 'Kasımpatı',
            'Poinsettia': 'Atatürk Çiçeği',
            'Fern': 'Eğrelti Otu',
            'Bird of Paradise': 'Cennet Kuşu Çiçeği',
            'String of Pearls': 'İnci Kolyesi',
            'String of Hearts': 'Kalp Kalbe Karşı',
            'Money Tree': 'Para Ağacı',
            'Rubber Plant': 'Kauçuk Ağacı',
            'Lithops': 'Yaşayan Taşlar',
            'Echeveria': 'Eçeverya',
            'Haworthia': 'Yılan Derisi Çiçeği',
            'Sedum': 'Damkoruğu',
            'Pilea': 'Pilea',
            'Zamioculcas': 'Zeze Çiçeği',
            'Maranta': 'Dua Çiçeği',
            'Stromanthe': 'Stromante',
            'Alocasia': 'Fil Kulağı',
            'Colocasia': 'Kolokazya',
            'Caladium': 'Kaladyum',
            'Polyscias': 'Aralya',
            'Schefflera': 'Şeflera',
            'Nephrolepis': 'Aşk Merdiveni',
            'Asplenium': 'Kuş Yuvası Eğreltisi',
            'Platycerium': 'Geyik Boynuzu Eğreltisi',
            'Adiantum': 'Venüs Saçı',
            'Pteris': 'Pteris',
            'Blechnum': 'Blechnum',
            'Cycas': 'Sago Palmiyesi',
            'Rhapis': 'Bambu Palmiyesi',
            'Howea': 'Kentia Palmiyesi',
            'Phoenix': 'Hurma Palmiyesi',
            'Washingtonia': 'Washington Palmiyesi',
            'Caryota': 'Balık Kuyruğu Palmiyesi',
            'Musa': 'Muz Ağacı',
            'Strelitzia': 'Starliçe',
            'Heliconia': 'Helikonya',
            'Canna': 'Tesbih Çiçeği',
            'Zingiber': 'Zencefil',
            'Curcuma': 'Zerdeçal',
            'Alpinia': 'Alpinya',
            'Costus': 'Kostus',
            'Calathea Makoyana': 'Tavus Kuşu Çiçeği',
            'Ctenanthe': 'Ctenanthe',
            'Oxalis': 'Uyku Çiçeği',
            'Senecio': 'İnci Tanesi',
            'Ceropegia': 'Kalp Kalbe',
            'Dischidia': 'Karınca Bitkisi',
            'Aeschynanthus': 'Ruj Çiçeği',
            'Columnea': 'Japon Balığı Çiçeği',
            'Episcia': 'Episcia',
            'Streptocarpus': 'Streptocarpus',
            'Sinningia': 'Bardak Menekşesi',
            'Primula': 'Çuha Çiçeği',
            'Viola': 'Hercai Menekşe',
            'Petunia': 'Petunya',
            'Pelargonium': 'Sakız Sardunya',
            'Fuchsia': 'Küpe Çiçeği',
            'Impatiens': 'Cam Güzeli',
            'Begonia Maculata': 'Çilli Begonya',
            'Pachypodium': 'Madagaskar Palmiyesi',
            'Adenium': 'Çöl Gülü',
            'Hoya': 'Hoya Çiçeği',
            'Araucaria': 'Salon Çamı',
            'Pachira': 'Para Ağacı',
            'Rhoeo': 'Musa’nın Beşiği',
            'Coleus': 'Kolyos',
            'Iresine': 'Kırmızı Yapraklı Kan Çiçeği',
            'Gynura': 'Kadife Çiçeği',
            'Hemigraphis': 'Mor İnci',
        },

        // Footer
        mission: 'Sürdürülebilir bir gelecek için teknoloji ve topluluk gücüyle çalışıyoruz.',
        copyright: '© 2026 GreenTrack - Tüm hakları saklıdır.',
        platform: 'PLATFORM',
        corporate: 'KURUMSAL',

        // Auth (Login/Signup/Forgot Password)
        welcome_back: 'Tekrar Hoş Geldiniz',
        sign_in_subtitle: 'Hesabınıza giriş yapın',
        email_address_label: 'E-posta Adresi',
        password_label: 'Şifre',
        confirm_password_label: 'Şifreyi Onayla',
        remember_me: 'Beni Hatırla',
        forgot_password: 'Şifremi Unuttum?',
        sign_in_btn: 'Giriş Yap',
        no_account: 'Hesabınız yok mu?',
        sign_up: 'Kayıt Ol',
        create_account_title: 'Hesap Oluştur',
        join_today: 'Bugün GreenTrack\'e Katılın',
        full_name_placeholder: 'Tam İsim',
        password_placeholder: 'Şifre',
        confirm_password_placeholder: 'Şifreyi Onayla',
        uploadPhoto: 'Fotoğraf Yükle',
        photoTooLarge: 'Fotoğraf 2 MB\u0027dan küçük olmalıdır',
        create_account_btn: 'Hesap Oluştur',
        already_have_account: 'Zaten bir hesabınız var mı?',
        sign_in_link: 'Giriş Yap',
        reset_password_title: 'Şifreyi Sıfırla',
        reset_password_subtitle: 'Sıfırlama bağlantısı almak için e-postanızı girin',
        send_reset_link_btn: 'Sıfırlama Bağlantısı Gönder',
        check_email_title: 'E-postanızı kontrol edin',
        check_email_desc: 'Eğer bu e-posta adresiyle bir hesap varsa, şifre sıfırlama talimatlarını gönderdik.',
        back_to_login: 'Girişe Dön',
        logout: 'Çıkış Yap',
        logoutConfirmTitle: 'Çıkış Yap?',
        logoutConfirmMessage: 'Çıkış yapmak istediğinizden emin misiniz?',
        verify_code_title: 'Kodu Doğrulayın',
        verify_code_subtitle: 'E-postanıza gönderilen 6 haneli kodu girin',
        verify_btn: 'Doğrula',
        new_password_title: 'Yeni Şifre Belirleyin',
        new_password_subtitle: 'Yeni şifrenizi aşağıya girin',
        new_password_placeholder: 'Yeni Şifre',
        reset_password_btn: 'Şifreyi Sıfırla',
        password_reset_success: 'Şifre Sıfırlama Başarılı!',
        redirecting_to_login: 'Giriş sayfasına yönlendiriliyorsunuz…',

        // Signup error/success messages
        error_email_registered: 'Bu e-posta zaten kayıtlı!',
        error_passwords_not_match: 'Şifreler eşleşmiyor!',
        error_server_connection: 'Sunucuya bağlanılamadı. Spring Boot çalışıyor mu?',
        registration_success_title: 'Kayıt Başarılı!',
        redirecting_to_dashboard: 'Panele yönlendiriliyorsunuz...',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en');

    const switchLanguage = (lang) => {
        setLanguage(lang);
    };

    const t = (key) => {
        return dictionary[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, switchLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => useContext(LanguageContext);
