spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/greentrack_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# --- EMAIL SETTINGS ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:kt7195741@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:qjbv gaym fnbb unqy}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# --- JWT SETTINGS ---
jwt.secret=${JWT_SECRET:dGhpc0lzQVNlY3JldEtleUZvckdyZWVuVHJhY2tKd3QyMDI2}
jwt.expiration=86400000
# --- UPLOAD SIZE LIMITS ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-http-form-post-size=10MB